name: Constantine Lignos - Research
markdown: kramdown
encoding: UTF-8
safe: true
lsi: false
highlighter: rouge
relative_permalinks: false
analytics: true
repository: constantinelignos/constantinelignos.github.io
